name: Documentation
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install packages
        run: |
          poetry run make config-poetry
          make install-all
      - name: Build and deploy documentation
        run: |
          cd docs/
          poetry run mkdocs gh-deploy --force --clean
