name: Nightly Tests
on:
  schedule:
    - cron: '40 9 * * *' # run at 9:40 AM UTC
  workflow_dispatch:  # manual trigger

jobs:
  doctest:
    uses: ./.github/workflows/doctest.yaml
  format:
    uses: ./.github/workflows/format.yaml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
  test:
    uses: ./.github/workflows/test.yaml
  test-deps:
    uses: ./.github/workflows/test-deps.yaml
