name: Nightly Package Tests
on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC
  workflow_dispatch:  # manual trigger

jobs:
  package:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install redcat

      - name: Run short experiment
        run: |
          python -c "import redcat; assert redcat.BatchList([1, 2, 3, 4, 5]).slice_along_batch(step=2).equal(redcat.BatchList([1, 3, 5]))"

  package-all:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install "redcat[all]"

      - name: Run short experiment
        run: |
          python -c "import torch; import redcat; assert redcat.BatchedTensor(torch.arange(10).view(2, 5)).sum().equal(torch.tensor(45.0))"
