name: Publish PyPI package
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Publish
        env:
          REDCAT_PYPI_TOKEN: ${{ secrets.REDCAT_PYPI_TOKEN }}
        run: |
          poetry run make publish-pypi
